# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8zXYlhh5f2_0qx_urjd9ZhF3WcBZCLb
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("diabetes_clean.csv")
df.head()

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title("🩺 Diabetes Analytics Dashboard")
st.markdown("""
This dashboard provides insights into diabetes trends based on age, gender, and health indicators.
Use the filters in the sidebar to explore the data.
""")

df = pd.read_csv("diabetes_clean.csv")

st.sidebar.header("🔎 Filters")
age_filter = st.sidebar.multiselect(
    "Select Age Group:",
    options=df["age_group"].unique(),
    default=df["age_group"].unique()
)

gender_filter = st.sidebar.multiselect(
    "Select Gender:",
    options=df["gender"].unique(),
    default=df["gender"].unique()
)

filtered_df = df[
    (df["age_group"].isin(age_filter)) &
    (df["gender"].isin(gender_filter))
]

st.subheader("📊 Key Metrics")
col1, col2, col3 = st.columns(3)

col1.metric("Total Records", len(filtered_df))
col2.metric("Diabetes Cases", filtered_df["diabetes"].sum())
col3.metric("Average BMI", round(filtered_df["bmi"].mean(), 2))

st.subheader("🧓 Diabetes by Age Group")
age_chart = filtered_df.groupby("age_group")["diabetes"].mean().sort_index()
st.bar_chart(age_chart)

st.subheader("👩‍⚕️ Diabetes by Gender")
gender_chart = filtered_df.groupby("gender")["diabetes"].mean()
st.bar_chart(gender_chart)

